# Required for UniformTypeIdentifiers
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]

# Inherited from YARP, see
# https://github.com/conda-forge/yarp-feedstock/blob/61774c75c96a20227c23596573e8845ff5fd8b63/recipe/conda_build_config.yaml#L1C1-L3C32
c_stdlib_version:          # [osx and x86_64]
  - '10.15'                # [osx and x86_64]
